[project]
name = "kpget"
license = "MIT"
version = "0.2.0"
description = "Fetch passwords from KeepassXC, sealed behind a Yubikey challenge-response"
authors = [
    { name = "Jeff Turner", email = "jeff@redradishtech.com" }
]
dependencies = [
    "keepassxc-proxy-client>=0.1.7",
    "pynacl>=1.5.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[project.scripts]
kpget = "kpget.cli:main"
kpget-secretspec-provider = "kpget.secretspec_provider:main"
kpget-secretspec-register = "kpget.secretspec_register:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/kpget"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
